[build]
    command = "npm run build"
    functions = "functions" # 넷니파이 서버리스 함수가 작선된 디렉토리를 지정
    publish = "dist" # 프로젝트 빌드 디렉토리 지정

[dev]
    framework = "#custom" # 샵 커스텀인 이유는 우리가 아래의 옵션을 입맛에 맞게 적용하기 위해 커스텀 모드를 선택한 것
    command = "npm run wpdev" # 연결할 프로젝트 개발서버를 실행
    targetPort = 8079 # 연결할 프로젝트 개발서버 포트 지정
    port = 8080 # 출력할 넷니파이 서버 포트를 지정
    publish = "dist" # 프로젝트 정적 콘텐츠 디렉토리 지정
    autoLaunch = false # 넷니파이 서버가 준비되면 자동으로 브라우저를열 것 인지를 지정